// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { getRequest } from "@tanstack/react-start/server";
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function readServerEnv(...names: string[]) {
  const env = typeof process !== "undefined" ? process.env : undefined;
  if (!env) return undefined;

  for (const name of names) {
    const value = env[name];
    if (value) return value;
  }

  return undefined;
}

export const requireSupabaseAuth = createMiddleware({ type: "function" }).server(
  async ({ next }) => {
    const SUPABASE_URL = readServerEnv("SUPABASE_URL", "VITE_SUPABASE_URL");
    const SUPABASE_PUBLISHABLE_KEY = readServerEnv(
      "SUPABASE_PUBLISHABLE_KEY",
      "VITE_SUPABASE_PUBLISHABLE_KEY",
      "SUPABASE_ANON_KEY",
      "VITE_SUPABASE_ANON_KEY",
    );

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [];
      if (!SUPABASE_URL) missing.push("SUPABASE_URL or VITE_SUPABASE_URL");
      if (!SUPABASE_PUBLISHABLE_KEY) {
        missing.push("SUPABASE_PUBLISHABLE_KEY or VITE_SUPABASE_PUBLISHABLE_KEY");
      }

      throw new Response(`Missing Supabase environment variables: ${missing.join(", ")}.`, {
        status: 500,
      });
    }

    let supabaseUrl: string;
    try {
      supabaseUrl = new URL(SUPABASE_URL).toString().replace(/\/$/, "");
    } catch {
      throw new Response("Invalid SUPABASE_URL. Use your full Supabase project URL.", {
        status: 500,
      });
    }

    const request = getRequest();

    if (!request?.headers) {
      throw new Response("Unauthorized: No request headers available", { status: 401 });
    }

    const authHeader = request.headers.get("authorization");

    if (!authHeader) {
      throw new Response("Unauthorized: No authorization header provided", { status: 401 });
    }

    if (!authHeader.startsWith("Bearer ")) {
      throw new Response("Unauthorized: Only Bearer tokens are supported", { status: 401 });
    }

    const token = authHeader.replace("Bearer ", "");
    if (!token) {
      throw new Response("Unauthorized: No token provided", { status: 401 });
    }

    const supabase = createClient<Database>(supabaseUrl, SUPABASE_PUBLISHABLE_KEY, {
      global: {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      },
      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
      },
    });

    const { data, error } = await supabase.auth.getClaims(token);
    if (error || !data?.claims) {
      throw new Response("Unauthorized: Invalid token", { status: 401 });
    }

    if (!data.claims.sub) {
      throw new Response("Unauthorized: No user ID found in token", { status: 401 });
    }

    return next({
      context: {
        supabase,
        userId: data.claims.sub,
        claims: data.claims,
      },
    });
  },
);
