// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function readServerEnv(...names: string[]) {
  const env = typeof process !== "undefined" ? process.env : undefined;
  if (!env) return undefined;

  for (const name of names) {
    const value = env[name];
    if (value) return value;
  }

  return undefined;
}

function requiredEnvMessage(missing: string[]) {
  return `Missing Supabase server environment variables: ${missing.join(", ")}. Add them to the Vercel project environment variables, then redeploy.`;
}

function createSupabaseAdminClient() {
  const SUPABASE_URL = readServerEnv("SUPABASE_URL", "VITE_SUPABASE_URL");
  const SUPABASE_SERVICE_ROLE_KEY = readServerEnv(
    "SUPABASE_SERVICE_ROLE_KEY",
    "SUPABASE_SERVICE_KEY",
    "SUPABASE_SECRET_KEY",
  );

  if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
    const missing = [];
    if (!SUPABASE_URL) missing.push("SUPABASE_URL or VITE_SUPABASE_URL");
    if (!SUPABASE_SERVICE_ROLE_KEY) missing.push("SUPABASE_SERVICE_ROLE_KEY");
    throw new Error(requiredEnvMessage(missing));
  }

  let supabaseUrl: string;
  try {
    supabaseUrl = new URL(SUPABASE_URL).toString().replace(/\/$/, "");
  } catch {
    throw new Error("Invalid SUPABASE_URL. Use your full Supabase project URL.");
  }

  return createClient<Database>(supabaseUrl, SUPABASE_SERVICE_ROLE_KEY, {
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    },
  });
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Import like: import { supabaseAdmin } from "@/integrations/supabase/client.server";
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
