// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function decodeJwtPayload(token: string): Record<string, unknown> | null {
  const [, payload] = token.split(".");
  if (!payload) return null;

  try {
    const base64 = payload.replace(/-/g, "+").replace(/_/g, "/");
    const padded = base64.padEnd(base64.length + ((4 - (base64.length % 4)) % 4), "=");
    return JSON.parse(atob(padded)) as Record<string, unknown>;
  } catch {
    return null;
  }
}

function readEnv(name: string, fallbackName = name) {
  const viteValue = import.meta.env[name];
  if (viteValue) return viteValue;

  if (typeof process !== "undefined") {
    return process.env[fallbackName];
  }

  return undefined;
}

function validateSupabaseKey(key: string, projectRef: string) {
  if (key.startsWith("sb_publishable_")) return;

  if (key.startsWith("sb_secret_")) {
    throw new Error(
      "Invalid Supabase key. Use a publishable key or legacy anon key in the browser, not a secret key.",
    );
  }

  const keyPayload = decodeJwtPayload(key);
  const keyIssuer = keyPayload?.iss;
  const keyRole = keyPayload?.role;
  const keyRef = keyPayload?.ref;

  if (!keyPayload) {
    throw new Error(
      "Invalid Supabase publishable key. Copy a publishable key or legacy anon public key from Supabase Project Settings > API Keys.",
    );
  }

  if (keyIssuer !== "supabase") {
    throw new Error(
      `Invalid Supabase legacy anon key issuer "${String(keyIssuer)}". Copy a fresh publishable key or legacy anon public key from Supabase Project Settings > API Keys.`,
    );
  }

  if (keyRole !== "anon") {
    throw new Error(
      `Invalid Supabase legacy anon key role "${String(keyRole)}". Use a publishable key or legacy anon public key, not the service role key.`,
    );
  }

  if (typeof keyRef === "string" && keyRef !== projectRef) {
    throw new Error(
      `Supabase configuration mismatch. The URL project ref "${projectRef}" does not match the anon key ref "${keyRef}".`,
    );
  }
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = readEnv("VITE_SUPABASE_URL", "SUPABASE_URL");
  const SUPABASE_PUBLISHABLE_KEY = readEnv(
    "VITE_SUPABASE_PUBLISHABLE_KEY",
    "SUPABASE_PUBLISHABLE_KEY",
  );

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    throw new Error(
      "Missing Supabase environment variables. Ensure SUPABASE_URL and SUPABASE_PUBLISHABLE_KEY (or VITE_ prefixed versions) are set in your .env file.",
    );
  }

  const projectRef = new URL(SUPABASE_URL).hostname.split(".")[0];
  validateSupabaseKey(SUPABASE_PUBLISHABLE_KEY, projectRef);

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
